version: '3'

services:
  metric-scraper:
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /metric-scraper
      environment:
        - DATABASE_SERVICE_NAME=POSTGRES_SQL
        - DATABASE_ENGINE=postgresql
        - DATABASE_NAME=postgres
        - POSTGRES_SQL_SERVICE_HOST=db
        - POSTGRES_SQL_SERVICE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - AUTH_TOKEN=_oauth_proxy=bWpob2xkZXJAY2x1c3Rlci5sb2NhbA==|1666869415|8t-XCsAdxxNDK9Z2Mm82hfupcII=; 01412cd97ff4944ee6e5a5210393d5a6=dd8a76dbd2a9bff22d181a22e9a79e7f
      privileged: true
      ports:
          - 9080:8000
      volumes:
        - '.:/metric-scraper/'
      links:
        - db
      depends_on:
        - db

  db:
    image: postgres:10.17
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: health-metrics
