version: '3'

services:
  health-monitor:
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /health-monitor
      entrypoint:
        - /health-monitor/run_server.sh
      environment:
        - DATABASE_SERVICE_NAME=POSTGRES_SQL
        - DATABASE_ENGINE=postgresql
        - DATABASE_NAME=postgres
        - POSTGRES_SQL_SERVICE_HOST=db
        - POSTGRES_SQL_SERVICE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - AUTH_TOKEN=
      privileged: true
      ports:
          - 9080:8000
      volumes:
        - '.:/health-monitor/'
      links:
        - db
      depends_on:
        - db

  db:
    image: postgres:10.17
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: health-monitor
