apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: metrics-db
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: metrics-db
    name: metrics-db
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: metrics-db
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: metrics-db
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - metrics-db
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - metrics-db
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers: 
        - env:
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
          - name: POSTGRESQL_USER
            value: ${DB_SECRET_NAME}
          - name: POSTGRESQL_PASSWORD
            value: ${DB_SECRET_NAME}
          - name: POSTGRESQL_DATABASE
            value: ${DB_SECRET_NAME}
          name: metrics-db
          image: registry.redhat.io/rhel8/postgresql-10
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: metrics-db-data
        volumes:
        - name: metrics-db-data
          persistentVolumeClaim:
            claimName: metrics-db
- apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: consoledot-health-metrics
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: consoledot-health-metrics
    name: consoledot-health-metrics
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: consoledot-health-metrics
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: consoledot-health-metrics
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - consoledot-health-metrics
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - consoledot-health-metrics
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers: 
        - env:
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_SERVICE_NAME
              value: POSTGRES_SQL
            - name: DATABASE_ENGINE
              value: postgresql
            - name: DATABASE_NAME
              value: ${DB_SECRET_NAME}
            - name: POSTGRES_SQL_SERVICE_HOST
              value: metrics-db
            - name: POSTGRES_SQL_SERVICE_PORT
              value: '5432'
            - name: DATABASE_USER
              value: ${DB_SECRET_NAME}
            - name: DATABASE_PASSWORD
              value: ${DB_SECRET_NAME}
            - name: AUTH_TOKEN
              value: _oauth_proxy=bWpob2xkZXJAY2x1c3Rlci5sb2NhbA==|1666869415|8t-XCsAdxxNDK9Z2Mm82hfupcII=; 01412cd97ff4944ee6e5a5210393d5a6=dd8a76dbd2a9bff22d181a22e9a79e7f
          name: metric-scraper
          image: quay.io/rh_ee_maholder/consoledot-health-metrics:latest
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: metrics-db
      template: metrics-db
    name: metrics-db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: metrics-db
    name: metrics-db
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
    selector:
      app: metrics-db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: The number of replicas to use in the deployment
  name: REPLICAS
  value: '1'
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Initial amount of memory
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of cpu
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 300m
- description: Maximum amount of cpu
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: '1'
- description: Name of DB secret
  name: DB_SECRET_NAME
  value: metrics-db