apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: grafana
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: grafana
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - grafana
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - grafana
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers: 
        - env:
          ports:
            - containerPort: 3000
              protocol: TCP
          name: grafana
          image: grafana/grafana:9.1.0
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: grafana-data
            persistentVolumeClaim:
              claimName: grafana-pvc
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: grafana
    name: grafana-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
    selector:
      app: grafana
    sessionAffinity: None
    type: ClusterIP 
  status:
    loadBalancer: {}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-route
spec:
  host: grafana-route-openshift.<Ingress_Domain> 
  port:
    targetPort: 3000
  to:
    kind: Service
    name: grafana-route
parameters:
- description: The number of replicas to use in the deployment
  name: REPLICAS
  value: '1'
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi